configfile: "workflow/config.yaml"


include: "rules/reference.smk"
include: "rules/fetch.smk"
include: "rules/genome.smk"
include: "rules/align.smk"


rule all:
    input:
        expand(
            "workflow/results/aligned/{sample}.sorted.bam.bai",
            sample=config["samples"],
        ),
