# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_piledownR_wrappers", use_symbols = TRUE, package_name = "piledownR")

#' @usage NULL
#' @useDynLib piledownR, .registration = TRUE
NULL

PileParams <- new.env(parent = emptyenv())

PileParams$new <- function(input_bam, lib_fragment_type, region, name, strand, regions, names, strands, seqs, starts, ends, regions_file, exclude_flags, index_path, concurrency, chunk_size, anchor_length) .Call(wrap__PileParams__new, input_bam, lib_fragment_type, region, name, strand, regions, names, strands, seqs, starts, ends, regions_file, exclude_flags, index_path, concurrency, chunk_size, anchor_length)

PileParams$generate_stream <- function() .Call(wrap__PileParams__generate_stream, self)

#' @export
`$.PileParams` <- function (self, name) { func <- PileParams[[name]]; environment(func) <- environment(); func }

#' @export
`[[.PileParams` <- `$.PileParams`

JunctionParams <- new.env(parent = emptyenv())

JunctionParams$new <- function(input_bam, lib_fragment_type, seqs, starts, ends, names, strands, junctions_file, exclude_flags, index_path, concurrency, anchor_length) .Call(wrap__JunctionParams__new, input_bam, lib_fragment_type, seqs, starts, ends, names, strands, junctions_file, exclude_flags, index_path, concurrency, anchor_length)

JunctionParams$generate_stream <- function() .Call(wrap__JunctionParams__generate_stream, self)

#' @export
`$.JunctionParams` <- function (self, name) { func <- JunctionParams[[name]]; environment(func) <- environment(); func }

#' @export
`[[.JunctionParams` <- `$.JunctionParams`


# nolint end
