# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_piledownR_wrappers", use_symbols = TRUE, package_name = "piledownR")

#' @usage NULL
#' @useDynLib piledownR, .registration = TRUE
NULL

PileParams <- new.env(parent = emptyenv())

PileParams$new <- function(input_bam, lib_fragment_type, region, name, strand, regions, region_names, region_strands, seqs, starts, ends, regions_file, exclude_flags, index_path, concurrency, chunk_size) .Call(wrap__PileParams__new, input_bam, lib_fragment_type, region, name, strand, regions, region_names, region_strands, seqs, starts, ends, regions_file, exclude_flags, index_path, concurrency, chunk_size)

PileParams$generate_stream <- function() .Call(wrap__PileParams__generate_stream, self)

#' @export
`$.PileParams` <- function (self, name) { func <- PileParams[[name]]; environment(func) <- environment(); func }

#' @export
`[[.PileParams` <- `$.PileParams`


# nolint end
